apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: naisdevice-approval
  namespace: nais
  labels:
    team: nais
spec:
  image: {{ image }}
  port: 80
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 90
  liveness:
    path: /
  readiness:
    path: /
  resources:
    limits:
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 16Mi
  ingresses:
    - https://naisdevice-approval.external.prod-gcp.nav.cloud.nais.io
  filesFrom:
    - emptyDir:
        medium: Disk
      mountPath: /var/cache/nginx/
    - emptyDir:
        medium: Disk
      mountPath: /var/run/