name: Build and deploy
on: push
permissions:
  contents: read
  id-token: write
jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
    steps:
      - uses: actions/checkout@v5
      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: nais
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-prod-gcp:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy to prod-gcp
    needs:
      - build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          VAR: image=${{ needs.build-and-push.outputs.image }}
          TELEMETRY: ${{ needs.build-and-push.outputs.telemetry }}
